apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: jupyter-spark-service
spec:
  selector:
    app: jupyter-spark
  ports:
    - protocol: "TCP"
      port: 3333
      targetPort: 8888
  clusterIP: None


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-spark
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-spark
  template:
    metadata:
      labels:
        app: jupyter-spark
    spec:
      serviceAccountName: spark
      containers:
      - name: jupyter-spark
        image: caiosgon3/jupyter-spark-driver:latest
        # command: ["ls"]
        ports:
        - containerPort: 8888

        # code.oak-tree.tech:5005/courseware/oak-tree/dataops-examples/spark-k8s-jupyter
# /usr/local/bin/jupyter-lab
# - ./hdfs:/hdfs
# - ./notebooks:/home/jovyan/work
