apiVersion: v1
kind: Service
metadata:
  namespace: spark
  name: jupyter-spark-service
spec:
  selector:
    app: jupyter-spark
  ports:
    - protocol: "TCP"
      port: 3333
      targetPort: 8888
  clusterIP: None

# kubectl -n spark port-forward pod/jupyter-pod 3333:8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-spark
  namespace: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-spark
  template:
    metadata:
      labels:
        app: jupyter-spark
    spec:
      serviceAccountName: spark
      containers:
      - name: jupyter-spark
        image: caiosgon3/jupyter-spark-driver:latest
        ports:
        - containerPort: 8888
